apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    appstudio.openshift.io/application: openshift-pipelines-index-4-19-1-21
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/url-org: openshift-pipelines
    release.appstudio.openshift.io/author: rh-ee-diagrawa
  generateName: openshift-pipelines-1-21-0-fbc-4-19-prod-release-
  namespace: tekton-ecosystem-tenant
spec:
  gracePeriodDays: 10
  releasePlan: openshift-pipelines-1-21-fbc-4-19-prod-release-as-op
  snapshot: openshift-pipelines-index-4-19-1-21-kg6k2
