name: openshift-pipelines-core
versions:
  next:
    version: next
    image-suffix: -rhel9
    auto-release: true
resources:
  - console-plugin
  - git-init
  - manual-approval-gate
  - pac-downstream
  - tekton-caches
  - tektoncd-chains
  - tektoncd-hub
  - tektoncd-pipeline
  - tektoncd-pruner
  - tektoncd-results
  - tektoncd-triggers