name: openshift-pipelines-core
versions:
  "1.21":
    version: "1.21"
    image-suffix: -rhel9
    auto-release: true
    released: true
resources:
  - console-plugin
  - git-init
  - manual-approval-gate
  - pac-downstream
  - tekton-caches
  - tektoncd-chains
  - tektoncd-hub
  - tektoncd-pipeline
  - tektoncd-pruner
  - tektoncd-results
  - tektoncd-triggers
