version: 1.22
patch-version: 1.22.0
image-suffix: "-rhel9"
branches:
  git-init:
    upstream: release-v1.2.x
  manual-approval-gate:
    upstream: release-v0.8.0
  opc:
    upstream: release-v1.19.x
  pipelines-as-code:
    upstream: release-v0.41.x
  tekton-assist:
    upstream: release-v0.1.x
  tekton-caches:
    upstream: release-v0.3.x
  tekton-kueue:
    upstream: release-v0.3.x
  tektoncd-chains:
    upstream: release-v0.26.x
  tektoncd-cli:
    upstream: release-v0.43.x
  tektoncd-hub:
    upstream: release-v1.23.6
  tektoncd-operator:
    upstream: main
  tektoncd-pipeline:
    upstream: release-v1.9.x
  tektoncd-pruner:
    upstream: release-v0.3.x
  tektoncd-results:
    upstream: release-v0.18.x
  tektoncd-triggers:
    upstream: release-v0.35.x
  syncer-service:
    upstream: release-v0.1.x
  multicluster-proxy-aae:
    upstream: release-v0.1.x
  operator:
    upstream: main
