version: "1.24"
image-suffix: -rhel9
patch-version: 1.24.0
branches:
  git-init:
    upstream: release-v1.2.x
  manual-approval-gate:
    upstream: release-v0.7.x
  opc:
    upstream: release-v1.19.x
  pipelines-as-code:
    upstream: release-v0.39.x
  tekton-assist:
    upstream: release-v0.1.x
  tekton-caches:
    upstream: release-v0.3.x
  tekton-kueue:
    upstream: release-v0.1.x
  tektoncd-chains:
    upstream: release-v0.26.x
  tektoncd-cli:
    upstream: release-v0.43.x
  tektoncd-hub:
    upstream: release-v1.23.x
  tektoncd-operator:
    upstream: release-v0.77.x
  tektoncd-pipeline:
    upstream: release-v1.7.x
  tektoncd-pruner:
    upstream: release-v0.3.x
  tektoncd-results:
    upstream: release-v0.17.x
  tektoncd-triggers:
    upstream: release-v0.34.x
