branches:
  git-init:
    upstream: release-v1.2.x
  manual-approval-gate:
    upstream: release-v0.7.0
  opc:
    upstream: release-v1.19.x
  pipelines-as-code:
    upstream: release-v0.39.x
  tekton-assist:
    upstream: release-v0.1.x
