apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    appstudio.openshift.io/application: openshift-pipelines-operator-1-19
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/url-org: openshift-pipelines
    release.appstudio.openshift.io/author: rh-ee-pbheeman
  generateName: openshift-pipelines-operator-1-19-0-prod-release-
  namespace: tekton-ecosystem-tenant
spec:
  data:
    releaseNotes:
      description: |
        Red Hat OpenShift Pipelines is a cloud-native continuous integration and
        delivery (CI/CD) solution for building pipelines using Tekton. Tekton is a
        flexible, Kubernetes-native, open-source CI/CD framework which enables
        automating deployments across multiple platforms such as Kubernetes, Serverless,
        and VMs by abstracting away the underlying details.

        Red Hat OpenShift Pipelines consists of:

        (needs to be updated)
        - Tekton Operator 0.76.x
        - Tekton Pipelines 1.0.x
        - Tekton Triggers 0.32.x
        - Tekton tkn CLI 0.41.0
        - Tekton Chains 0.25.x (GA)
        - Pipelines-as-Code 0.35.x (GA)
        - Tekton Hub 1.21.x (TP)
        - Tekton Result 0.15.x (TP)
        - Console Plugin 1.19.x (TP)
        - manual-approval-gate 0.6.x (TP)
        - tektoncd-pruner 0.1.x (TP)
        - tekton-cache 0.2.x (TP)
        - opc 1.19.x

        ## Features
        - Standard CI/CD pipelines definition

        - Easy to extend and integrate with existing tools

        - Portable across any Kubernetes platform

        - Designed for microservices and decentralized teams

        - Integrated with OpenShift Developer Console

        - Build images with Kubernetes tools such as S2I, Buildah, Buildpacks, Kaniko,
          etc.

        - Deploy applications to multiple platforms such as Kubernetes, Serverless, and
          VMs

        - Scale pipelines on-demand

        - Enhance supply chain security with Tekton Chains (Technology Preview)

        - Install and deploy Tekton Hub (Technology Preview) with custom catalog on
          enterprise cluster

        - Maintain pipelines definitions as part of an application repository with
          Pipelines-as-Code (PAC) (General Availability)

          For more information, see the Release Notes on any one of the following
          platforms:

        - Customer Portal:
          https://docs.redhat.com/en/documentation/red_hat_openshift_pipelines/1.19/html/about_openshift_pipelines/about-pipelines

        - OpenShift documentation:
          https://docs.redhat.com/en/documentation/red_hat_openshift_pipelines/1.19/html/release_notes/op-release-notes-1-19#op-release-notes-1-19_op-release-notes
      issues:
        fixed:
          - id: SRVKP-6980
            source: issues.redhat.com
      package-maintainer: pipelines-bots@redhat.com
      references:
        - https://docs.redhat.com/en/documentation/red_hat_openshift_pipelines
      release-name: openshift-pipelines-1.19.0
      solution: |
        Before applying this update, make sure all previously released advisory
        relevant to your system have been applied.
        For details on how to apply this update, refer to:
        https://access.redhat.com/articles/11258
      synopsis: "Red Hat OpenShift Pipelines Release 1.19.0"
      topic: |
        The 1.19.0 release of Red Hat OpenShift Pipelines Operator..
        For more details see [product documentation](https://docs.redhat.com/en/documentation/red_hat_openshift_pipelines).
      type: RHEA
  gracePeriodDays: 10
  releasePlan: openshift-pipelines-operator-1-19-prod-release-as-op
  snapshot: openshift-pipelines-operator-1-19-xnbbh
  