repo: p12n-console-plugin
upstream: openshift-pipelines/console-plugin
no-prefix-upstream: true
components:
  - name: console-plugin
    prefetch-input: |-
      [{"type": "yarn"}, {"type": "npm", "path": ".konflux/npm"}]
