name: operator
components:
  - name: index-4.17
    dockerfile: .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
    nudges: [ "" ]
    no-image-suffix: true
tekton:
  watched-sources: ( ".konflux/olm-catalog/index/***".pathChanged())
