name: tektoncd-pipeline
upstream: tektoncd/pipeline
no-prefix-upstream: true
components:
  - name: controller
  - name: entrypoint
  - name: events
  - name: nop
  - name: resolvers
    tekton:
      watched-sources: ("dependencies/tini/***".pathChanged() || ".konflux/patches/***".pathChanged() || ".konflux/rpms/***".pathChanged() )
  - name: sidecarlogresults
  - name: webhook
  - name: workingdirinit
