- name: openshift-pipelines-core
  repos:
    - git-init
    - manual-approval-gate
    - pipelines-as-code
    - tekton-assist
    - tekton-caches
    - tekton-kueue
    - tektoncd-chains
    - tektoncd-hub
    - tektoncd-pipeline
    - tektoncd-pruner
    - tektoncd-results
    - tektoncd-triggers
    - syncer-service
    - multicluster-proxy-aae
    - console-plugin
    - tektoncd-cli
    - opc
    - serve-tkn-cli
    - operator
