- name: openshift-pipelines-index-4.21
  repos:
    - operator-index-4.21
- name: openshift-pipelines-index-4.20
  repos:
    - operator-index-4.20
- name: openshift-pipelines-index-4.19
  repos:
    - operator-index-4.19
- name: openshift-pipelines-index-4.18
  repos:
    - operator-index-4.18
- name: openshift-pipelines-index-4.17
  repos:
    - operator-index-4.17
- name: openshift-pipelines-index-4.16
  repos:
    - operator-index-4.16
