name: console-plugin
components:
  - name: console-plugin
    prefetch-input: |-
      [{"type": "rpm", "path": ".konflux/rpms"}, {"type": "yarn"}]
tekton:
  watched-sources: '"***".pathChanged()'
branches:
  - name: release-v1.17.x
    versions:
      - 1.17
