name: tektoncd-git-clone
upstream: tektoncd-catalog/git-clone
components:
  - name: git-init
    no-image-prefix: true
branches:
  - name: release-v1.21.x
    upstream: main
    versions:
      - "1.21"
