name: operator
components:
  - name: index-4.14
    dockerfile: .konflux/olm-catalog/index/v4.14/Dockerfile.catalog
    nudges: [ "" ]
tekton:
  watched-sources: ( ".konflux/olm-catalog/index/***".pathChanged())
branches:
  - name: release-v1.19.x
    versions:
      - "1.19"
