name: operator
components:
  - name: index-4.16
    dockerfile: .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
    nudges: [ "" ]
tekton:
  watched-sources: ( ".konflux/olm-catalog/index/***".pathChanged())
branches:
  - name: release-v1.20.x
    versions:
      - "1.20"
