name: operator
components:
  - name: index-4.20
    dockerfile: .konflux/olm-catalog/index/v4.19/Dockerfile.catalog
    nudges: [ "" ]
tekton:
  watched-sources: ( ".konflux/olm-catalog/index/***".pathChanged())
branches:
  - name: release-v1.21.x
    versions:
      - "1.21"
