name: secret-syncer
components:
  - name: syncer
tekton:
  watched-sources: '"***".pathChanged()'
branches:
  # uncomment below line to get nightly builds
  # - name: main
  - name: next
    versions:
      - next
