name: tektoncd-pipeline
upstream: tektoncd/pipeline
components:
  - name: controller
  - name: entrypoint
  - name: events
  - name: nop
  - name: resolvers
  - name: sidecarlogresults
  - name: webhook
  - name: workingdirinit
branches:
  - name: next
    upstream: release-v1.9.x
    versions:
      - next
