name: tekton-kueue
upstream: konflux-ci/tekton-kueue
components:
  - name: kueue
    image-prefix: tekton-
    prefetch-input: |
      {"type": "gomod", "path": "upstream"}
branches:
  - name: next
    upstream: main
    versions:
      - next
