name: tektoncd-pruner
upstream: tektoncd/pruner

components:
  - name: controller
    image-prefix: pruner-
  - name: webhook
    image-prefix: pruner-
branches:
  - name: release-v1.21.x
    upstream: release-v0.3.x
    versions:
      - "1.21"
