name: tektoncd-triggers
upstream: tektoncd/triggers
components:
  - name: controller
  - name: webhook
  - name: core-interceptors
  - name: eventlistenersink
branches:
  - name: release-v1.21.x
    upstream: release-v0.33.x
    versions:
      - "1.21"
