name: tektoncd-results
upstream: tektoncd/results
components:
  - name: api
  - name: watcher
  - name: retention-policy-agent
branches:
  - name: release-v1.19.x]
    upstream: release-v0.15.x
    versions:
      - "1.19"
