name: tektoncd-hub
upstream: tektoncd/hub
components:
  - name: db-migration
  - name: api
  - name: ui
    prefetch-input: |-
      [{"type": "npm", "path": "upstream/ui"}, {"type": "rpm", "path": ".konflux/rpms"}]
branches:
  # - name: main
  - name: release-v1.19.x
    upstream: release-v1.21.1
    versions:
      - "1.19"
