name: tektoncd-results
upstream: tektoncd/results
components:
  - name: api
  - name: watcher
  - name: retention-policy-agent
branches:
  - name: release-v1.21.x
    upstream: release-v0.16.x
    versions:
      - "1.21"
