name: Sync Hack Repo Labels
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/labels.yml'
      - '.github/workflows/sync-org-labels.yaml'
      - 'config/downstream/repos/*'
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  repository-projects: write
jobs:
  sync-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Sync labels
        uses: EndBug/label-sync@v2
        with:
          token: ${{ secrets.HACK_LABELS_SECRET }}
          config-file: '.github/labels.yml'
      - name: Sync labels to each repo
        run: |
          for repo in $(yq -N e '.repo // .name' config/downstream/repos/*.yaml | sort -u) ; do
            echo "Syncing labels for $repo"
            gh label clone openshift-pipelines/hack -R openshift-pipelines/$repo --force || true
          done
        env:
          GH_TOKEN: ${{ secrets.OPENSHIFT_PIPELINES_ROBOT }}

