name: Sync Organization Labels
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/labels.yml'
      - '.github/workflows/sync-org-labels.yaml'
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  repository-projects: write
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Sync labels
        uses: EndBug/label-sync@v2
        with:
          token: ${{ secrets.OPENSHIFT_PIPELINES_ROBOT }}
          config-file: '.github/labels.yml'
      - name: Sync labels to each repo
        run: |
          gh repo list openshift-pipelines --json name -q '.[].name' > repos.txt
          for repo in $(cat repos.txt); do
            echo "Syncing labels for $repo"
            gh label clone openshift-pipelines/hack -R openshift-pipelines/$repo --force
          done
        env:
          GH_TOKEN: ${{ secrets.OPENSHIFT_PIPELINES_ROBOT }}

