apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    appstudio.openshift.io/application: openshift-pipelines-core-1-19
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/url-org: openshift-pipelines
    release.appstudio.openshift.io/author: rh-ee-sashture
  generateName: openshift-pipelines-core-1-19-4-stage-release-
  namespace: tekton-ecosystem-tenant
spec:
  data:
    releaseNotes:
      description: |
        Red Hat OpenShift Pipelines is a cloud-native continuous integration and
        delivery (CI/CD) solution for building pipelines using Tekton. Tekton is a
        flexible, Kubernetes-native, open-source CI/CD framework which enables
        automating deployments across multiple platforms such as Kubernetes, Serverless,
        and VMs by abstracting away the underlying details.
      cves:
        - key: CVE-2025-6547
          component: tektoncd-hub-1-19-api
        - key: CVE-2025-6545
          component: tektoncd-hub-1-19-db-migration
        - key: CVE-2025-9287
          component: tektoncd-hub-1-19-ui
        - key: CVE-2025-9288
          component: tektoncd-hub-1-19-api
        - key: CVE-2025-64756
          component: tektoncd-hub-1-19-db-migration
      issues:
        fixed:
          - id: SRVKP-8484
            source: issues.redhat.com
          - id: SRVKP-8894
            source: issues.redhat.com
          - id: SRVKP-9177
            source: issues.redhat.com
          - id: SRVKP-9454
            source: issues.redhat.com
          - id: SRVKP-6960
            source: issues.redhat.com
          - id: SRVKP-8112
            source: issues.redhat.com
          - id: SRVKP-8198
            source: issues.redhat.com
          - id: SRVKP-8480
            source: issues.redhat.com
          - id: SRVKP-8891
            source: issues.redhat.com
          - id: SRVKP-9204
            source: issues.redhat.com
          - id: SRVKP-6211
            source: issues.redhat.com
          - id: SRVKP-8571
            source: issues.redhat.com
          - id: SRVKP-8269
            source: issues.redhat.com
      package-maintainer: pipelines-bots@redhat.com
      references:
        - https://docs.redhat.com/en/documentation/red_hat_openshift_pipelines
      release-name: openshift-pipelines-1.19.4
      solution: |
        Before applying this update, make sure all previously released advisory
        relevant to your system have been applied.
        For details on how to apply this update, refer to:
        https://access.redhat.com/articles/11258
      synopsis: "Red Hat OpenShift Pipelines Release 1.19.4"
      topic: |
        The 1.19.4 release of Red Hat OpenShift Pipelines Operator..
        For more details see [product documentation](https://docs.redhat.com/en/documentation/red_hat_openshift_pipelines).
      type: RHSA
  gracePeriodDays: 10
  releasePlan: openshift-pipelines-core-1-19-stage-release-as-op
  snapshot: openshift-pipelines-core-1-19-2bvlg